apiVersion: apps/v1
kind: Deployment
metadata:
  name: halobuzz-backend
  labels:
    app: halobuzz-backend
    version: v1
spec:
  replicas: 3  # Start with 3 replicas, can be scaled up
  selector:
    matchLabels:
      app: halobuzz-backend
  template:
    metadata:
      labels:
        app: halobuzz-backend
        version: v1
    spec:
      containers:
      - name: halobuzz-backend
        image: halobuzz/backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: halobuzz-secrets
              key: redis-url
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: halobuzz-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: halobuzz-secrets
              key: jwt-secret
        - name: AGORA_APP_ID
          valueFrom:
            secretKeyRef:
              name: halobuzz-secrets
              key: agora-app-id
        - name: AGORA_APP_CERTIFICATE
          valueFrom:
            secretKeyRef:
              name: halobuzz-secrets
              key: agora-app-certificate
        - name: AGORA_ADAPTIVE_BITRATE
          value: "true"
        - name: AGORA_GLOBAL_CDN
          value: "true"
        - name: AGORA_AUTO_SCALING
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: halobuzz-backend-service
  labels:
    app: halobuzz-backend
spec:
  selector:
    app: halobuzz-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: halobuzz-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: halobuzz-backend
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: halobuzz-config
data:
  NODE_ENV: "production"
  AGORA_ADAPTIVE_BITRATE: "true"
  AGORA_GLOBAL_CDN: "true"
  AGORA_AUTO_SCALING: "true"
  MAX_CONNECTIONS_PER_USER: "5"
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"

---
apiVersion: v1
kind: Secret
metadata:
  name: halobuzz-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==  # redis://localhost:6379
  mongodb-uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9oYWxvYnV6eg==  # mongodb://localhost:27017/halobuzz
  jwt-secret: eW91ci1qd3Qtc2VjcmV0  # your-jwt-secret
  agora-app-id: eW91ci1hZ29yYS1hcHAtaWQ=  # your-agora-app-id
  agora-app-certificate: eW91ci1hZ29yYS1hcHAtY2VydGlmaWNhdGU=  # your-agora-app-certificate
