version: '3.9'
services:
  mongo:
    image: mongo:7
    container_name: halobuzz-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: halobuzz-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  ai:
    build:
      context: ./ai-engine
    restart: unless-stopped
    env_file:
      - .env.ai.local
    ports:
      - "5020:5020"

  backend:
    build:
      context: ./backend
    depends_on:
      - mongo
      - redis
      - ai
    restart: unless-stopped
    env_file:
      - .env.backend.local
    environment:
      - TZ=Australia/Sydney
    ports:
      - "5010:5010"

volumes:
  mongo_data:


