global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'halobuzz-backend'
    static_configs:
      - targets: ['backend:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']