global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@halobuzz.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://webhook:5001/'

  - name: 'email'
    email_configs:
      - to: 'admin@halobuzz.com'
        subject: 'HaloBuzz Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'slack'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts'
        title: 'HaloBuzz Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
