name: Admin Dashboard CI/CD Pipeline

on:
  push:
    branches: [master, develop, staging]
    paths:
      - 'admin/**'
      - '.github/workflows/admin-ci.yml'
  pull_request:
    branches: [master, develop]
    paths:
      - 'admin/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '9.1.0'

jobs:
  lint-typecheck-build:
    name: Lint, Type Check & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: admin/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./admin
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./admin
        run: pnpm run lint || true

      - name: Run TypeScript type check
        working-directory: ./admin
        run: pnpm run type-check

      - name: Build Next.js application
        working-directory: ./admin
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: admin-build
          path: admin/.next/
          retention-days: 7

  deploy-staging:
    name: Deploy to Vercel Staging
    runs-on: ubuntu-latest
    needs: [lint-typecheck-build]
    if: github.ref == 'refs/heads/staging'
    environment:
      name: admin-staging
      url: https://admin-staging.halobuzz.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          working-directory: ./admin

  deploy-production:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    needs: [lint-typecheck-build]
    if: github.ref == 'refs/heads/master'
    environment:
      name: admin-production
      url: https://admin.halobuzz.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./admin
