name: Deploy AI Engine to Railway
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ai-engine/**"
      - ".github/workflows/railway-ai.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-engine
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ai-engine/pnpm-lock.yaml
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript typecheck
        run: pnpm tsc --noEmit || echo "TypeScript errors found but continuing deployment"
        
      - name: Build AI engine
        run: pnpm run build
        
      - name: Security tests
        run: pnpm test --if-present || echo "Tests failed but continuing deployment"
        
      - name: Deploy to Railway
        uses: railwayapp/action-deploy@v2
        with:
          service: ai-engine
          path: ai-engine
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Wait for deployment
        run: sleep 30
        
      - name: Health check with retry
        run: |
          for i in {1..10}; do
            if curl -f -s "${{ secrets.AI_URL }}/healthz" > /dev/null; then
              echo "✅ AI Engine health check passed"
              exit 0
            fi
            echo "⏳ Attempt $i/10: AI Engine not ready, waiting 15s..."
            sleep 15
          done
          echo "❌ AI Engine health check failed after 10 attempts"
          exit 1
        env:
          AI_URL: ${{ secrets.AI_URL }}
          
      - name: Output deploy URL
        run: echo "🤖 AI Engine deployed to: ${{ secrets.AI_URL }}"
